[project]
name = 'Galactic-Civilization-Resource-Exchange'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.interstellar-resource-tokenization]
path = 'contracts/interstellar-resource-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.planetary-development-index]
path = 'contracts/planetary-development-index.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
